# Generated by Django 4.2.13 on 2025-07-12 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VariacionBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("precio_base", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tipo_producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variaciones_base",
                        to="catalogo.tipoproducto",
                    ),
                ),
                (
                    "valores",
                    models.ManyToManyField(
                        related_name="variaciones_base", to="catalogo.valoratributo"
                    ),
                ),
            ],
            options={
                "ordering": ["tipo_producto__nombre"],
            },
        ),
    ]
