# Generated by Django 4.2.23 on 2025-07-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_variacionbase'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='producto',
            name='categorias',
            field=models.ManyToManyField(related_name='productos', to='catalogo.categoria'),
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
    ]
