# Generated by Django 4.2.23 on 2025-06-27 02:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único para el tipo de trabajo (ej: Globos, Stickers).', max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recibido', models.DateField(default=django.utils.timezone.now)),
                ('prioridad', models.CharField(choices=[('Urgente', 'Urgente'), ('Normal', 'Normal')], default='Normal', max_length=10)),
                ('estado', models.CharField(choices=[('Recibido', 'Recibido'), ('En Proceso', 'En Proceso'), ('Completado', 'Completado')], default='Recibido', max_length=20)),
                ('cliente', models.CharField(max_length=150)),
                ('numero', models.CharField(blank=True, help_text='Número de orden o identificador único.', max_length=50)),
                ('fecha_completado', models.DateField(blank=True, null=True)),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestor_tareas.tipotrabajo')),
            ],
            options={
                'ordering': ['-fecha_recibido', 'prioridad'],
            },
        ),
    ]
