# Generated by Django 4.2.23 on 2025-07-01 13:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único para el tipo de trabajo (ej: Globos, Stickers).', max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recibido', models.DateField(default=django.utils.timezone.now, help_text='Fecha en que se recibió la tarea.')),
                ('prioridad', models.CharField(choices=[('Urgente', 'Urgente'), ('Normal', 'Normal')], default='Normal', help_text='Nivel de urgencia de la tarea.', max_length=10)),
                ('estado', models.CharField(choices=[('Recibido', 'Recibido'), ('En Proceso', 'En Proceso'), ('Completado', 'Completado')], default='Recibido', help_text='Estado actual de la tarea.', max_length=20)),
                ('cliente', models.CharField(help_text='Nombre del cliente que solicita la tarea.', max_length=150)),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono opcional del cliente.', max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la tarea.')),
                ('fecha_completado', models.DateField(blank=True, help_text="Fecha en que la tarea cambió a estado 'Completado'. Se rellena automáticamente.", null=True)),
                ('is_visible', models.BooleanField(default=True, help_text='Indica si la tarea es visible en la lista principal. Desmarcar para archivar.')),
                ('tipo', models.ForeignKey(blank=True, help_text='Categoría o tipo de trabajo a realizar.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestor_tareas.tipotrabajo')),
            ],
            options={
                'ordering': ['-fecha_recibido', 'prioridad'],
            },
        ),
    ]
