# Generated by Django 4.2.23 on 2025-06-27 03:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_tareas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='numero',
        ),
        migrations.AddField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada de la tarea.'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Indica si la tarea es visible en la lista principal. Desmarcar para archivar.'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono opcional del cliente.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='cliente',
            field=models.CharField(help_text='Nombre del cliente que solicita la tarea.', max_length=150),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('Recibido', 'Recibido'), ('En Proceso', 'En Proceso'), ('Completado', 'Completado')], default='Recibido', help_text='Estado actual de la tarea.', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_completado',
            field=models.DateField(blank=True, help_text="Fecha en que la tarea cambió a estado 'Completado'. Se rellena automáticamente.", null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_recibido',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha en que se recibió la tarea.'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('Urgente', 'Urgente'), ('Normal', 'Normal')], default='Normal', help_text='Nivel de urgencia de la tarea.', max_length=10),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tipo',
            field=models.ForeignKey(blank=True, help_text='Categoría o tipo de trabajo a realizar.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestor_tareas.tipotrabajo'),
        ),
    ]
