# Generated by Django 5.2.4 on 2025-07-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestor_tareas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tarea",
            options={"ordering": ["orden", "-fecha_recibido", "prioridad"]},
        ),
        migrations.AddField(
            model_name="tarea",
            name="orden",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Número que define el orden de prioridad de la tarea.",
                null=True,
            ),
        ),
    ]
