# Generated by Django 5.2.6 on 2025-09-11 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogo",
            "0003_alter_producto_unique_together_producto_categorias_and_more",
        ),
        ("gestor_tareas", "0003_stickerprice_detalletarea"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StickerPrice",
        ),
        migrations.AddField(
            model_name="detalletarea",
            name="variacion",
            field=models.ForeignKey(
                blank=True,
                help_text="Variación del catálogo para referencias existentes.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalogo.variacionproducto",
            ),
        ),
        migrations.AlterField(
            model_name="detalletarea",
            name="color",
            field=models.ForeignKey(
                blank=True,
                help_text="Color del producto (ValorAtributo).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="catalogo.valoratributo",
            ),
        ),
        migrations.AlterField(
            model_name="detalletarea",
            name="tamano",
            field=models.ForeignKey(
                blank=True,
                help_text="Tamaño del producto (ValorAtributo).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="catalogo.valoratributo",
            ),
        ),
        migrations.AlterField(
            model_name="detalletarea",
            name="tipo_producto",
            field=models.ForeignKey(
                blank=True,
                help_text="Tipo de producto según el catálogo.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalogo.tipoproducto",
            ),
        ),
    ]
