# Generated by Django 4.2.23 on 2025-06-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único para la categoría (ej: Comida, Transporte, Oficina)', max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único para la cuenta (ej: Banco Principal, Tarjeta de Crédito, Efectivo)', max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
