# Generated by Django 4.2.23 on 2025-06-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaz', '0002_registro_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='nombre',
            field=models.CharField(help_text='Nombre único para la cuenta (ej: Banco Principal, Efectivo)', max_length=100, unique=True),
        ),
    ]
